### ISSUE TITLE
Downloading video help

### ISSUE THREAD

**Issue by asdfghjkl87755** [pzhlkj6612/streamlink-eplus_jp-object_storage#5]
Dear sir 
Please tell the way to download video from elearn.brilliantpala.org step by step i have no knowledge in downloading videos via ffmpeg or any other software

Username 256436
Password 256436

As you directed i found the key in the preview tab but what is the next step to do ?

i didnt understood you said about saving as curl

please look the below link with key and key url

video link
https://elearn.brilliantpala.org/courses/103/contents/42178/

m3u8 url :  https://d1j3vi2u94ebt0.cloudfront.net/institute/brilliantpalalms/courses/copy-of-jee-main-mfeatbaypup3/videos/transcoded/d65d4372c03642cf80a08bf51a54172f/720p/video.m3u8

key - Jmv��KͬN6.�}i�
key url  (https://elearn.brilliantpala.org/api/v2.5/video_contents/42178/key/)

**Comment by pzhlkj6612** [comment]
I guess you know how to **REPLY** an existing issue (#2) raised by you, don't you?
