### ISSUE TITLE
Brilliant pala elearn

### ISSUE THREAD

**Issue by asdfghjkl87755** [pzhlkj6612/streamlink-eplus_jp-object_storage#8]
Hey 👋 I previously contacted you for downloading videos from brilliant pala elearn and classes
But when I try to download the below error is coming
 
Brilliantpala:Elearn] Downloading login page
ERROR: An extractor error has occurred. (caused by KeyError('csrfmiddlewaretoken')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

Student id 292870
Password 292870

Also push the update to ytdlp bcz I am using ytdlp stable version through ytdlnis android app for downloading 
Please update for both elearn.brilliantpala.org and classes.brilliantpala.org

**Comment by asdfghjkl87755** [comment]
~ $ yt-dlp -vU --embed-thumbnail
--embed-metadata
--username 303465
--password 303465 https://elearn.brilliantpala.org/courses/303/contents/149625

Latest version: stable@2024.04.09 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.04.09 from yt-dlp/yt-dlp)
[Brilliantpala:Elearn] Downloading login page
[debug] Command-line config: ['--config-locations', '/data/user/0/com.deniscerri.ytdl/cache/config-TERMINAL[1713877481243].txt', '--cookies', '/data/user/0/com.deniscerri.ytdl/cache/cookies.txt', '--add-header', 'User-Agent:Mozilla/5.0 (Linux; Android 10; Lenovo TB-X306F Build/QP1A.190711.020; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/123.0.6312.118 Safari/537.36', '-P', '/storage/emulated/0/Android/data/com.deniscerri.ytdl/files/downloads//TERMINAL/49', '--no-cache-dir', '--ffmpeg-location', '/data/app/com.deniscerri.ytdl-SFePdeRXHhS517Web3COGw==/lib/arm64/libffmpeg.so']
[debug] | Config "/data/user/0/com.deniscerri.ytdl/cache/config-TERMINAL[1713877481243].txt": ['-vU', '--embed-thumbnail', '--embed-metadata', '--username', 'PRIVATE', '--password', 'PRIVATE', 'https://elearn.brilliantpala.org/courses/303/contents/149625']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8 (No ANSI), error utf-8 (No ANSI), screen utf-8 (No ANSI)
[debug] yt-dlp version stable@2024.04.09 from yt-dlp/yt-dlp [ff0779267] (zip)
[debug] Python 3.8.0 (CPython aarch64 64bit) - Linux-4.9.190+-aarch64-with-libc (OpenSSL 1.1.1t  7 Feb 2023, libc)
[debug] exe versions: ffmpeg 5.1 (setts), ffprobe 5.1
[debug] Optional libraries: Cryptodome-3.17, mutagen-1.46.0, sqlite3-3.30.1
[debug] Proxy map: {}
[debug] Request Handlers: urllib
[debug] Loaded 1810 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
ERROR: An extractor error has occurred. (caused by KeyError('csrfmiddlewaretoken')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "/data/user/0/com.deniscerri.ytdl/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/extractor/common.py", line 731, in extract
    self.initialize()
  File "/data/user/0/com.deniscerri.ytdl/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/extractor/common.py", line 637, in initialize
    self._perform_login(username, password)
  File "/data/user/0/com.deniscerri.ytdl/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/extractor/brilliantpala.py", line 36, in _perform_login
    self._set_cookie(self._DOMAIN, 'csrftoken', login_form['csrfmiddlewaretoken'])
KeyError: 'csrfmiddlewaretoken'

**Comment by pzhlkj6612** [comment]
Hi, @asdfghjkl87755. I think you should not open two issues in each repositories. Anyway, I think I'll take a look if I'm free.

**Comment by asdfghjkl87755** [comment]
Okay 👍 please do it before April 30 because the course will get end by may 1

**Comment by pzhlkj6612** [comment]
Fixed in https://github.com/yt-dlp/yt-dlp/pull/9788.
